ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "
- podman
- ubuntu
- php
- curl
- caddy
- openssl
- ssh
- thumbor
- mysql
- aws
- redis
- solr
- react
- redux
- webpack
- lodash
- symfony

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

DESCRIPTION_KEYWORDS_FILTER:
- ThisIsACaseSensitiveExample

DESCRIPTION_KEYWORDS_FILTER_I:
- code-projects
- nuuo
- Ampache
- campcodes
- WordPress
- SourceCodester
- DedeCMS
- Dell
- Apache Airflow
- arubaos
- ruijie
- wolfssh
- phpmyfaq
- home-made.io
- oroplatform
- lepton
- hgw
- cyberaz0r
- gibbon
- buddypress
- WooCommerce
- CardOS
- CIGESv2
- Bref
- FreeScout
- SeaCMS
- Niushop
- Netcome
- FileMaker
- dzzoffice
- VvvebJs
- Sentrifugo
- Apollo Router
- RSSHub
- Artica-Proxy
- ZhiCms
- Panabit
- MISP
- tramyardg
- MyPrestaModules
- Best-Kit
- Elspec
- Netentsec
- Open Source Medicine Ordering System
- Employee Management System
- Fujian Kelixin
- BestWebSoft
- LDAP Account Manager
- flusity
- kishor-23
- 74CMS
- MAGESH-K21
- RaspAP
- Snowflake Hive
- Surya2Developer
- Greek Universities Network
- eyoucms
- Healthcare-Chatbot
- Phpgurukul
- vantage6
- TurboBoost
- Webedition CMS
- Vinchin
- PaperCut
- Student Enrollment In PHP
- Piwigo
- CMS Made Simple
- TIBCO Software
- Apache Pulsar Proxy
- FreeScout
- Gacjie
- Vela
- My Food Recipe
- Student Information Chatbot
- keerti1924
- CodeAstro
- boyiddha
- Hotel Booking Management
- Hospital Management System
- Byzro
- FreeRTOS
- Devolutions
- Arista
- MediaTek
- Stupid Simple CMS
- Nway
- Laragon
- SocialMediaWebsite
- zhimengzhe
- Element Android
- Dataease
- Simple Student Attendance System
- Projectworlds
- open-emr
- osuuu
- Subrion
- ZenML
- Ctcms
- Oozie Workflow Scheduler
- Beijing Baichuo
- Apache James
- AnythingLLM
- Dynamic Lab Management System
- Demososo
- itsourcecode
- Laravel
- oFono
- Kubean
- mailcow
- Roundcube
- microweber
- PuneethReddyHC
- E-Negosyo
- Zscaler
- Alien Technology
- Naukowa
- Kashipara
- Okta
- azzaroco
- WP OnlineSupport
- Crocoblock
- ZZCMS
- VOID CODERS
- Woo Products
- Hamed Naderfar
- eyecix
- WPDeveloper
- PluginOps
- Geek Code Lab
- DouPHP
- Pi-hole
- DedeBIZ
- Tosei
- xiaohe4966
- LimeSurvey
- TpMeCMS
- Ericsson
- TeamCity
- Xyzscripts
- Pligg CMS
- Keyfactor Command
- Hotel Management System
- School Management System
- Warehouse Inventory System
- Pharmacy Management System
- Blood Bank And Donation Management System

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc
- podman
- container
- ubuntu
- php
- curl
- caddy
- openssl
- ssh
- thumbor
- mysql
- aws
- redis
- solr
- react
- redux
- webpack
- lodash
- symfony

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_FILTER_I:
- code-projects
- nuuo
- Ampache
- campcodes
- WordPress
- SourceCodester
- DedeCMS
- Dell
- Apache Airflow
- arubaos
- ruijie
- wolfssh
- phpmyfaq
- home-made.io
- oroplatform
- lepton
- hgw
- cyberaz0r
- gibbon
- buddypress
- WooCommerce
- CardOS
- CIGESv2
- Bref
- FreeScout
- SeaCMS
- Niushop
- Netcome
- FileMaker
- dzzoffice
- VvvebJs
- Sentrifugo
- Apollo Router
- RSSHub
- Artica-Proxy
- ZhiCms
- Panabit
- MISP
- tramyardg
- MyPrestaModules
- Best-Kit
- Elspec
- Netentsec
- Open Source Medicine Ordering System
- Employee Management System
- Fujian Kelixin
- BestWebSoft
- LDAP Account Manager
- flusity
- kishor-23
- 74CMS
- MAGESH-K21
- RaspAP
- Snowflake Hive
- Surya2Developer
- Greek Universities Network
- eyoucms
- Healthcare-Chatbot
- Phpgurukul
- vantage6
- TurboBoost
- Webedition CMS
- Vinchin
- PaperCut
- Student Enrollment In PHP
- Piwigo
- CMS Made Simple
- TIBCO Software
- Apache Pulsar Proxy
- FreeScout
- Gacjie
- Vela
- My Food Recipe
- Student Information Chatbot
- keerti1924
- CodeAstro
- boyiddha
- Hotel Booking Management
- Hospital Management System
- Byzro
- FreeRTOS
- Devolutions
- Arista
- MediaTek
- Stupid Simple CMS
- Nway
- Laragon
- SocialMediaWebsite
- zhimengzhe
- Element Android
- Dataease
- Simple Student Attendance System
- Projectworlds
- open-emr
- osuuu
- Subrion
- ZenML
- Ctcms
- Oozie Workflow Scheduler
- Beijing Baichuo
- Apache James
- AnythingLLM
- Dynamic Lab Management System
- Demososo
- itsourcecode
- Laravel
- oFono
- Kubean
- mailcow
- Roundcube
- microweber
- PuneethReddyHC
- E-Negosyo
- Zscaler
- Alien Technology
- Naukowa
- Kashipara
- Okta
- azzaroco
- WP OnlineSupport
- Crocoblock
- ZZCMS
- VOID CODERS
- Woo Products
- Hamed Naderfar
- eyecix
- WPDeveloper
- PluginOps
- Geek Code Lab
- DouPHP
- Pi-hole
- DedeBIZ
- Tosei
- xiaohe4966
- LimeSurvey
- TpMeCMS
- Ericsson
- TeamCity
- Xyzscripts
- Pligg CMS
- Keyfactor Command
- Hotel Management System
- School Management System
- Warehouse Inventory System
- Pharmacy Management System
- Blood Bank And Donation Management System

PRODUCT_KEYWORDS_FILTER:
- ThisIsACaseSensitiveExample
