ALL_VALID: no

DESCRIPTION_KEYWORDS_I:
- privilege escalation
- escalation
- privesc
- high integrity
- elevated privilege
- escalation of privilege
- " sudo "
- " suid "
- " pe "
- " UAC "
- User Account Control
- linpeas
- winpeas
- docker
- kubernetes
- " lxc "
- podman
- ubuntu
- php
- curl
- caddy
- openssl
- ssh
- thumbor
- mysql
- nginx
- aws
- redis
- solr
- munin
- graylog
- nagios
- ossec
- react
- redux
- webpack
- lodash
- symfony

DESCRIPTION_KEYWORDS:
- ThisIsACaseSensitiveExample

DESCRIPTION_KEYWORDS_FILTER:
- Ampache

DESCRIPTION_KEYWORDS_FILTER_I:
- thisisacaseinsensitiveexample

PRODUCT_KEYWORDS_I:
- sudo
- docker
- kubernetes
- lxc
- podman
- container
- ubuntu
- php
- curl
- caddy
- openssl
- ssh
- thumbor
- mysql
- nginx
- aws
- redis
- solr
- munin
- graylog
- nagios
- ossec
- react
- redux
- webpack
- lodash
- symfony

PRODUCT_KEYWORDS:
- ThisIsACaseSensitiveExample

PRODUCT_KEYWORDS_FILTER_I:
- thisisacaseinsensitiveexample

PRODUCT_KEYWORDS_FILTER:
- Ampache

